View(dados_fazenda)
media_area <- mean(dados_fazenda$Area_m2)
media_insumo <- mean(dados_fazenda$Insumo_L)
dados_soja <- dados_fazenda %>% filter(Cultura == "Soja")
dados_Cafe <- dados_fazenda %>% filter(Cultura == "Café")
media_soja <- mean(dados_soja$Area_m2)
media_cafe <- mean(dados_Cafe$Area_m2)
media_insumo_soja <- mean(dados_soja$Insumo_L)
media_insumo_cafe <- mean(dados_Cafe$Insumo_L)
desvio_area <- sd(dados_fazenda$Area_m2)
desvio_insumo <- sd(dados_fazenda$Insumo_L)
desvio_area <- sd(dados_fazenda$Area_m2)
desvio_insum_cafe <- sd(dados_Cafe$Insumo_L)
desvio_insum_soja <- sd(dados_soja$Insumo_L)
desvio_area_cafe <- sd(dados_Cafe$Area_m2)
desvio_area_soja <- sd(dados_soja$Area_m2)

cat("\n" , "===========================================", "\n")
cat("   FARMTECH SOLUTIONS - RELATÓRIO ENRIQUECIDO\n")
cat("===========================================", "\n\n")

cat("--- ESTATÍSTICAS GERAIS DA FAZENDA ---\n")
cat("Média da Área Total:      ", round(media_area, 2), " m²\n")
cat("Desvio Padrão da Área:    ", round(desvio_area, 2), " m²\n")
cat("Média de Insumos:         ", round(media_insumo, 2), " L\n")
cat("Desvio Padrão de Insumos: ", round(desvio_insumo, 2), " L\n\n")

cat("--- ANÁLISE ESPECÍFICA: CAFÉ ---\n")
cat("Média da Área (Café):     ", round(media_cafe, 2), " m²\n")
cat("Desvio Padrão (Café):     ", round(desvio_area_cafe, 2), " m²\n")
cat("Média de Insumo (Café):   ", round(media_insumo_cafe, 4), " L\n")
cat("Desvio Padrão (Café):     ", round(desvio_insum_cafe, 4), " L\n\n")

cat("--- ANÁLISE ESPECÍFICA: SOJA ---\n")
cat("Média da Área (Soja):     ", round(media_soja, 2), " m²\n")
cat("Desvio Padrão (Soja):     ", round(desvio_area_soja, 2), " m²\n")
cat("Média de Insumo (Soja):   ", round(media_insumo_soja, 2), " L\n")
cat("Desvio Padrão (Soja):     ", round(desvio_insum_soja, 2), " L\n")

cat("\n", "===========================================", "\n")
cat("           FIM DO RELATÓRIO ESTATÍSTICO\n")
cat("===========================================", "\n")
